### ISSUE TITLE
How is the Mailchimp integration intended to work?

### ISSUE THREAD

**Issue by joshuajonah** [ulule/django-courriers#4]
I set this up with my mailchimp account and tested it, it doesn't give any errors but no emails are sent, lists are not created, and it outputs some json in the logs. I would assume it should upload the list of subscribers to make a mailchimp subscriber list on the site, but it doesn't seem to do anything.

**Comment by thoas** [comment]
You have to register manually your users to the list or use the [subscribe](https://github.com/ulule/django-courriers/blob/master/courriers/tasks.py#L6) task.

If you don't use celery, you can call the task without celery by calling the **register** method of the backend.
